---
# tasks file for aws-cli
- name: 'Install Python PIP'
  tags: 'aws-cli'
  become: 'yes'
  yum: >
    pkg=python-pip
    state=latest

- name: 'Install AWS CLI'
  tags: 'aws-cli'
  become: 'yes'
  pip: >
    name=awscli
    state=latest

- name: 'Create the AWS config directory'
  tags: 'aws-cli'
  become: 'yes'
  file: >
    path=/home/{{ ansible_ssh_user }}/.aws
    state=directory
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0755

- name: 'Copy AWS CLI config'
  tags: 'aws-cli'
  become: 'yes'
  template: >
    src=aws_cli_config.j2
    dest=/home/{{ ansible_ssh_user }}/.aws/config
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0644

- name: 'Copy AWS CLI config'
  tags: 'aws-cli'
  become: 'yes'
  template: >
    src=aws_cli_credentials.j2
    dest=/home/{{ ansible_ssh_user }}/.aws/credentials
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0644
