---
# tasks file for gerrit (mySQL specific)

- name: Ensure python-mysqldb is installed.
  sudo: yes
  apt: pkg=python-mysqldb state=installed 
  tags:
    - gerrit
    - mysql

- name: Create Gerrit mySQL database
  sudo: yes
  mysql_db: >
    name={{ gerrit_database_db }}
    login_host={{gerrit_database_hostname}}
    login_password={{gerrit_database_hostname_pass}}
    login_user={{gerrit_database_main_username}}
    encoding=utf8
    state=present
  tags:
    - gerrit
    - mysql

- name: Create Gerrit mySQL database user
  mysql_user:
    name={{gerrit_database_username}}
    host={{gerrit_host_name_in_mysql}}
    login_host={{gerrit_database_hostname}}
    password={{gerrit_database_password}}
    login_user={{gerrit_database_main_username}}
    login_password={{gerrit_database_hostname_pass}}
    priv={{gerrit_database_db}}.*:ALL
    state=present
  tags:
    - gerrit
    - mysql
