---
- name: Installs Jenkins slave for ARM project
  hosts: arm-jenkins-slaves
  sudo: true
   	
  vars:
    - ansible_ssh_user: centos
    - ac_flavor: arm
    - arm_mysql_master_pass: root

    - java_version: 8
    - java_subversion: 92

    - remove_old_java_version: 'true'
    - java_old_version: 'jdk-1.7.0_75-fcs.x86_64'


  roles:
#    - f500.dumpall
      
#    - hosts
     - dns
     - williamyeh.oracle-java
     - geerlingguy.git
     - geerlingguy.repo-epel
     - common
     - pcextreme.mariadb
     - activemq    
     - mysql-utils
