---
- name: Installs Artifactory server
  hosts: artifactory-servers
  sudo: true
   	
  vars:
    - ansible_ssh_user: centos
    - java_version: 8
    - java_subversion: 66

  roles:
    - kbrebanov.unzip
    #- geerlingguy.java
    - williamyeh.oracle-java

    - pcextreme.mariadb
    - bbaassssiiee.artifactory