
- src: https://github.com/shelleg/ansible-role-artifactory.git
  name: ansible-role-artifactory

- src: https://github.com/shelleg/ansible-role-dbmanage.git
  name: dbmanage

- src: geerlingguy.git
  version: 1.0.6

- src: geerlingguy.java 
  version: 1.1.1

- src: franklinkim.vim
  version: 1.1.0

- src: geerlingguy.repo-epel
  version: 1.0.5


