---
- name: Installs ipp compilation server 
  hosts: tag_Name_awsrdsanjer
  #gather_facts: no
  sudo: true
 
  vars:
    - ansible_ssh_user: centos
    - ansible_distribution: CentOS

  roles:
    - dns
    - common
    - williamyeh.oracle-java
    - tomcat
    - geerlingguy.sonar
  
  tasks:
