---
- name: Installs TEST Gerrit Code Review
  hosts: test-gerrit-ubuntu-servers
  sudo: true
 
  vars:
    ansible_ssh_user: ubuntu

    # custom smtp configuration
    gerrit_custom_smtp: true
    gerrit_sendemail_smtp_server: 'smtp.office365.com'
    gerrit_smtp_port: 587
    gerrit_smtp_encryption_medhod: 'tls'
    gerrit_smtp_username: 'devopssmtp@audiocodes.com'
    gerrit_smtp_password: 'ilov3AWScloud$' # need to encrypt !
    gerrit_mail_from_addr: 'test_gerrit@audiocodes.com'
    # session expiration ... 
    gerrit_web_sessions_maxage: '1 year'

    gerrit_host_name: test-gerrit

    gerrit_canonical_web_url: http://test-gerrit:8080/
    gerrit_database_db: test_reviewdb
    gerrit_database_username: testgerrit
    gerrit_database_password: test

#    gerrit_host_name: '172.16.133.%'
#    gerrit_database_hostname: 'rdci.c1tyrsglic7l.eu-central-1.rds.amazonaws.com'
#    gerrit_database_main_username: root
#    gerrit_database_hostname_pass: '1TTqYAHtdT'


  roles:
  #  - dns
    - kbrebanov.gerrit
#    - amos.gerrit
  tasks:
