---
# features.mysql or features.postgresql should be true

# Download & install
- include: install.yml

# Configure Jenkins reverse proxy via nginx
- include: nginx.yml
  tags:
    - nginx

# Database configuration, one or the other
- include: postgresql.yml
  when: artifactory_database == 'postgresql'
- include: mysql.yml
  when: artifactory_database == 'mysql'
