---
- name: restart jenkins
  service: name=jenkins state=restarted

- name: nginx reload
  service: name=nginx state=reloaded
  sudo: yes

- name: nginx start
  service: name=nginx state=started
  sudo: yes

- name: nginx stop
  service: name=nginx state=stopped
  sudo: yes
