---
# defaults file for aws-cli
aws_cli_user: "{{ ansible_ssh_user }}"
aws_output_format: 'json'
aws_region: "{{ aws_region }}"
aws_access_key_id: "{{ aws_access_key }}"
aws_secret_access_key: "{{ aws_secret_key }}"
