---
- debug: msg="aws_access_key is {{ aws_access_key }}, aws_secret_key is {{ aws_secret_key }} aws_region is {{aws_region }}"

- include: create-ec2-instance.yml 
  when: splitted is undefined

- include: create-ec2-instance-large_volumes.yml 
  when: splitted is defined

- debug: var=item
  with_items: "{{ ec2.instances }}"

- add_host: name={{ item.private_ip }} >
            groups=tag_Type_{{ec2_tag_Type}},tag_Environment_{{ec2_tag_Environment}}
            ec2_region={{ec2_region}} 
            ec2_tag_Name={{ec2_tag_Name}}
            ec2_tag_Type={{ec2_tag_Type}}
            ec2_tag_Environment={{ec2_tag_Environment}}
            ec2_ip_address={{item.private_ip}}
  with_items: "{{ ec2.instances }}"

- name: Wait for the instances to boot by checking the ssh port
  wait_for: host="{{item.private_ip}}" port=22 delay=60 timeout=320 state=started
  with_items: "{{ ec2.instances }}"
