- name: "Disable selinux"
  selinux: state=disabled

- name: "Set hostname"
  shell:
    hostnamectl set-hostname {{ inventory_hostname }}

- name: "Add {{ ansible_hostname }} to hosts file"
  lineinfile:
    dest=/etc/hosts
    insertafter=EOF
    line="127.0.0.1 {{ inventory_hostname }}"
    regexp="^127\.0\.0\.1 {{ inventory_hostname }}$"
    state=present
  tags:
  - setHosts

- name: "Add AudioCodes group"
  group: name={{ ac.group }}

- name: "Add AudioCodes user"
  user: name={{ ac.user }} group={{ ac.group }} home={{ ac.home_dir }}

- name: "Configure AudioCodes as sudoer"
  template: src=ac dest=/etc/sudoers.d/ac mode=0644 owner=root group=root

- name: "Create AudioCodes runtime directory"
  file: path="{{ ac.runtime_dir }}/tools/" recurse=yes state=directory mode=0755 owner={{ ac.user }} group={{ ac.group }}

- name: "Create AudioCodes config directory"
  file: path="{{ ac.runtime_dir }}/conf/" recurse=yes state=directory mode=0755 owner={{ ac.user }} group={{ac.group }}

- name: "Install packadges we want on all hosts"
  yum: name={{ item }} state=latest 
  with_items:
    - bash-completion
    - vim
    - epel-release
    - python-pip
    - python-boto
    - bash-completion
    - awscli
    - "{{ ns_pkgs }}"
  tags:
  - packs

- name: perform nfs-client operations
  include: nfs-client.yml
  when: nfs_client == true

- name: install python-redis for ansible caching
  pip: name=redis
  when: ansible_connection == 'local'

- include: aliases.yml
  when: ansible_connection == 'local'

- include: ssl.yml
  when: ssl_enabled
  tags:
  - ssl

- include: dist-keys.yml
  when: dist_keys is defined
  tags: 
  - dist-keys

- include: clean-keys.yml
  when: clean_keys is defined
  tags: 
  - clean-keys

#- include: install-ansible.yml
#  when: install_ansible is defined
#  tags:
#  - install-ansible
