---
- name: restart sonar
#  service: name=sonar state=restarted
  sudo: yes
  shell: service sonar restart
  notify:  wait for sonar to start

- name: wait for sonar to start
  wait_for: 
     port={{sonar_port}}
     timeout=180
