---
# tasks for activemq installation


- name: 'verify presence of activemq_file'
  stat: path=/tmp/{{activemq_file}}
  register: download 

- name: 'download activemq'
  get_url: url={{activemq_url}} dest=/tmp/{{activemq_file}}
  retries: 3
  when: not download.stat.exists 

- name: Unzip activemq.
  unarchive:
    src: /tmp/{{activemq_file}}
    dest: /opt
    copy: no
    creates: /usr/local/sonar/COPYING


