---
# handlers file for bbaassssiiee.artifactory
- name: 'start artifactory'
  sudo: yes
  service: name=artifactory state=started
  tags:
    - init

- name: 'restart artifactory'
  sudo: yes
  service: name=artifactory state=restarted

- name: nginx reload
  service: name=nginx state=reloaded
  sudo: yes

- name: nginx start
  service: name=nginx state=started
  sudo: yes

- name: nginx stop
  service: name=nginx state=stopped
  sudo: yes
