---
# defaults file for gerrit

#gerrit_download_server: https://gerrit-releases.storage.googleapis.com
gerrit_download_server: https://artifactory/libs-release-local/com/google/gerrit/gerrit-war/2.12_patched
gerrit_download_maven: false
#gerrit_version: 2.12
gerrit_version: war-2.12_patched
#gerrit_sha256sum: 8f2e2e61b939664a20a025ef4f99095c08be14342ea5457bf5613bccedabcd27
gerrit_sha256sum: 563b74438bb48c7c4b0a78d860aed3e819bffe953b91b8785d7e0477f7bcfd20
gerrit_install_plugins: []

gerrit_auth_type: 'LDAP'
gerrit_canonical_web_url: 'https://gerrit/'
gerrit_container_java_home: /usr/lib/jvm/java-7-oracle
gerrit_host_name: 'gerrit'
gerrit_host_name_in_mysql: '172.16.133.%'
gerrit_database_type: 'mysql'
gerrit_database_db: 'reviewdb'
gerrit_database_username: 'gerrit2'
gerrit_database_password: 'gerrit2'
gerrit_database_hostname: 'rdci.c1tyrsglic7l.eu-central-1.rds.amazonaws.com'
gerrit_database_hostname_pass: '1TTqYAHtdT'
gerrit_database_main_username: 'root'
gerrit_httpd_listen_url: 'proxy-https://*:8080/'
gerrit_sendemail_smtp_server: 'localhost'
gerrit_sshd_listen_address: '*:29418'
gerrit_proxy_port: '80'
gerrit_http_port: '8080'
gerrit_https_port: 443
gerrit_ssl_cert: "{{ ac_ssl_wc_cer_location }}"
gerrit_ssl_key: "{{ ac_ssl_wc_key_location }}"

gerrit_logdir: /var/gerrit/logs

gerrit_ldap_server: ldaps://aclads01.corp.audiocodes.com:3269
gerrit_ldap_username: aws
gerrit_ldap_password: AudiocodesAWS
gerrit_ldap_account_base: dc=corp,dc=audiocodes,dc=com
gerrit_ldap_group_base: dc=corp,dc=audiocodes,dc=com
gerrit_account_email_address: ${mail.toLowerCase}

gerrit_plugins_allow_remote_admin: true

gerrit_plugins:
  - url: https://artifactory/plugins-release-local/com/audiocodes/gwapp/plugins/acGerrit/ac-gerrit/2.12-47-g507bab9
    name: ac-gerrit-2.12-47-g507bab9.jar
  - url: https://artifactory/plugins-release-local/com/googlesource/gerrit/plugins/download/download-commands/2.12-1-g2a0e5ac
    name: download-commands-2.12-1-g2a0e5ac.jar
  - url: https://artifactory/plugins-release-local/com/googlesource/gerrit/plugins/gitblit/gitblit/2.12.162.1
    name: gitblit-2.12.162.1.jar
  - url: https://artifactory/plugins-release-local/com/googlesource/gerrit/plugins/reviewnotes/reviewnotes/2.12
    name: reviewnotes-2.12.jar
