- name: "Add gerrit to hosts file"
  lineinfile: dest=/etc/hosts insertafter=EOF line="{{hosts_gerrit_ip}} gerrit" state=present
  
- name: "Add artifactory to hosts file"
  lineinfile: dest=/etc/hosts insertafter=EOF line="{{hosts_artifactory_ip}} artifactory" state=present