---
workspace: /root

# Default to the latest LTS release.
sonar_download_url: https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-4.5.6.zip
sonar_version_directory: sonarqube-4.5.6

sonar_host_name: '172.16.145.11'

# MySQL database connection details.
sonar_mysql_username: sonar
sonar_mysql_password: sonar

sonar_mysql_host: 'rdci.c1tyrsglic7l.eu-central-1.rds.amazonaws.com'
sonar_mysql_port: "3306"
sonar_mysql_database: sonar
sonar_database_hostname_pass: '1TTqYAHtdT'
sonar_database_main_username: root

