---
- name: Setup SBC slave
  hosts: tag_Name_sbc_build_slave
  become: true

  pre_tasks:
   - include_vars: ec2_vars/ec2.yml
 
  roles:
    - geerlingguy.repo-epel 
    - common

  vars:
    nfs_client: true

  tasks:
    
